spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application: 
    name: banyan-config-client
eureka: 
  client:
    service-url:
      defaultZone: http://eureka7003:eureka7003@eureka-7003.com:7003/eureka/
---
server:
  port: 8102
spring:
  profiles: beta
  application: 
    name: banyan-config-client
eureka: 
  client:
    service-url:
      defaultZone: http://eureka7003:eureka7003@eureka-7003.com:7003/eureka/
